language: php
php:
  - '5.6'

services:
    - mysql

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - npm install

script:
  - sudo php artisan migrate:refresh --seed

