language: php

php:
  - '5.6'

services:
    - mysql

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

before_script:
  - mysql -e 'create database homestead_test;'

script:
  - php artisan migrate:refresh --seed
