services:
    - mysql:latest

before_script:
    - bash ci/docker_install.sh > /dev/null
    - composer install --no-progress

job1:
    script:
        - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"
        - php artisan migrate:refresh --seed

language: php
php:
  - '5.6'