language: php
php:
  - '5.6'

services:
    - mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

job1:
    script:
        - sudo php artisan migrate:refresh --seed

